USE [master]
GO

/****** Object:  Database [TestDb3]    Script Date: 12/6/2023 2:30:08 PM ******/
CREATE DATABASE [TestDb3]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TestDb3', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\TestDb3.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TestDb3_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\TestDb3_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TestDb3].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TestDb3] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TestDb3] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TestDb3] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TestDb3] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TestDb3] SET ARITHABORT OFF 
GO

ALTER DATABASE [TestDb3] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TestDb3] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TestDb3] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TestDb3] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TestDb3] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TestDb3] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TestDb3] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TestDb3] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TestDb3] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TestDb3] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TestDb3] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TestDb3] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TestDb3] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TestDb3] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TestDb3] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TestDb3] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TestDb3] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TestDb3] SET RECOVERY FULL 
GO

ALTER DATABASE [TestDb3] SET  MULTI_USER 
GO

ALTER DATABASE [TestDb3] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TestDb3] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TestDb3] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TestDb3] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TestDb3] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TestDb3] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [TestDb3] SET QUERY_STORE = OFF
GO

ALTER DATABASE [TestDb3] SET  READ_WRITE 
GO


